properties([
    pipelineTriggers([
        pollSCM('H/2 * * * *')
    ])
])

node {
    def buildOk = false
    def testOk = false

    try {
        stage('Build') {
            sh 'python3 -m py_compile sources/add2vals.py sources/calc.py'
            buildOk = true
        }

        stage('Test') {
            if (buildOk) {
                try {
                    sh 'pytest --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
                    testOk = true
                } finally {
                    junit 'test-reports/results.xml'
                }
            }
        }

        stage('Deliver') {
            if (testOk) {
                sh 'pyinstaller --onefile sources/add2vals.py'
                archiveArtifacts artifacts: 'dist/add2vals', fingerprint: true
            }
        }
    } finally {
        echo 'Pipeline selesai'
    }
}